name: backend

on:
  push:
    branches:
      - main
  
  schedule:
    - cron: '0 12 * * *'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5
  
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: backend/dist

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BACKEND_SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.BACKEND_SERVER_KNOWN_HOSTS }}

      - run: rsync -v dist/index.js ${SERVER_USER}@${SERVER_IP}:~/index.js
        env:
          SERVER_USER: ${{ secrets.BACKEND_SERVER_USER }}
          SERVER_IP: ${{ secrets.BACKEND_SERVER_IP }}
      - run: rsync -v ${SERVER_USER}@${SERVER_IP}:~/index.js ${SERVER_USER}@10.0.1.40:~/index.js
        env:
          SERVER_USER: ${{ secrets.BACKEND_SERVER_USER }}
          SERVER_IP: ${{ secrets.BACKEND_SERVER_IP }}
      - run: ssh -i ${SERVER_SSH_KEY} ${SERVER_USER}@10.0.1.40 "sudo systemctl restart backend"
        env:
          SERVER_USER: ${{ secrets.BACKEND_SERVER_USER }}
          SERVER_IP: ${{ secrets.BACKEND_SERVER_IP }}
          SERVER_SSH_KEY: ${{ secrets.BACKEND_SERVER_SSH_KEY }}
      - run: ssh -i ${SERVER_SSH_KEY} ${SERVER_USER}@10.0.1.40 systemctl status backend
        env:
          SERVER_USER: ${{ secrets.BACKEND_SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.BACKEND_SERVER_SSH_KEY }}
      - run: exit


