name: frontend

on:
  push:
    branches:
      - main
  
  schedule:
    - cron: '0 12 * * *'

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: .next
          path: frontend/.next
          retention-days: 5

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: aws s3 sync .next s3://aws-test-app-frontend/.next --exact-timestamps --region ap-northeast-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BACKEND_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BACKEND_AWS_SECRET_ACCESS_KEY }}

          
            

